<PopupLayout>:
    orientation: 'vertical'
    Label:
        text: root.text

<OkPopup>:
    Button:
        size_hint_y: None
        height: '40dp'
        text: 'OK'
        on_release: root.dispatch('on_answer')


<ConfirmPopup>:
	BoxLayout:
		size_hint_y: None
		height: '40dp'
		Button:
			text: 'Yes'
			on_release: root.dispatch('on_answer', True)
		Button:
			text: 'No'
			on_release: root.dispatch('on_answer', False)
